package com.haier.webservices.client.acg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-08-14T16:55:52.868+08:00
 * Generated source version: 3.2.8
 *
 */
@WebService(targetNamespace = "http://acg.server.webservices.haier.com/", name = "AcgPushService")
@XmlSeeAlso({ObjectFactory.class})
public interface AcgPushService {

    @WebMethod
    @RequestWrapper(localName = "pushContractor", targetNamespace = "http://acg.server.webservices.haier.com/", className = "com.haier.webservices.client.acg.PushContractor")
    @ResponseWrapper(localName = "pushContractorResponse", targetNamespace = "http://acg.server.webservices.haier.com/", className = "com.haier.webservices.client.acg.PushContractorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.webservices.client.acg.AjaxJson pushContractor(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.haier.webservices.client.acg.Dealer arg0
    );
}
