
package com.haier.webservices.client.hps.file;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-05-13T20:34:15.506+08:00
 * Generated source version: 3.2.8
 *
 */

public class FileWebService_FileWebServiceImplPort_Server{

    protected FileWebService_FileWebServiceImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new FileWebServiceImplPortImpl();
        String address = "http://10.138.10.68:8090/soap/file";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new FileWebService_FileWebServiceImplPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
