package com.haier.webservices.client.hps.file;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-05-13T20:34:15.486+08:00
 * Generated source version: 3.2.8
 *
 */
@WebService(targetNamespace = "http://file.manage.hps.com/", name = "FileWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface FileWebService {

    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://file.manage.hps.com/", className = "com.haier.webservices.client.hps.file.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://file.manage.hps.com/", className = "com.haier.webservices.client.hps.file.UploadResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haier.webservices.client.hps.file.ResInfoFile upload(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.haier.webservices.client.hps.file.FileWrapper arg0
    );
}
