
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.haier.webservices.client.hps.file;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-05-13T20:34:15.457+08:00
 * Generated source version: 3.2.8
 *
 */

@WebService(
                      serviceName = "FileWebService",
                      portName = "FileWebServiceImplPort",
                      targetNamespace = "http://file.manage.hps.com/",
                      wsdlLocation = "http://10.138.10.68:8090/soap/file?wsdl",
                      endpointInterface = "com.haier.webservices.client.hps.file.FileWebService")

public class FileWebServiceImplPortImpl implements FileWebService {

    private static final Logger LOG = Logger.getLogger(FileWebServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.haier.webservices.client.hps.file.FileWebService#upload(com.haier.webservices.client.hps.file.FileWrapper arg0)*
     */
    public com.haier.webservices.client.hps.file.ResInfoFile upload(com.haier.webservices.client.hps.file.FileWrapper arg0) {
        LOG.info("Executing operation upload");
        System.out.println(arg0);
        try {
            com.haier.webservices.client.hps.file.ResInfoFile _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
