
package com.haier.webservices.client.hps.file;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-05-13T20:34:15.403+08:00
 * Generated source version: 3.2.8
 *
 */
public final class FileWebService_FileWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://file.manage.hps.com/", "FileWebService");

    private FileWebService_FileWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = FileWebService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        FileWebService_Service ss = new FileWebService_Service(wsdlURL, SERVICE_NAME);
        FileWebService port = ss.getFileWebServiceImplPort();

        {
        System.out.println("Invoking upload...");
        com.haier.webservices.client.hps.file.FileWrapper _upload_arg0 = null;
        com.haier.webservices.client.hps.file.ResInfoFile _upload__return = port.upload(_upload_arg0);
        System.out.println("upload.result=" + _upload__return);


        }

        System.exit(0);
    }

}
