package com.haier.mdm.yhcx;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-26T13:38:46.104+08:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "mdmgeneralbankinterface_client_ep",
                  wsdlLocation = "http://10.135.1.129:7778/soa-infra/services/interface/MDMGeneralBankInterface/mdmgeneralbankinterface_client_ep?WSDL",
                  targetNamespace = "http://xmlns.oracle.com/Interface/MDMGeneralBankInterface/MDMGeneralBankInterface")
public class MdmgeneralbankinterfaceClientEp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/Interface/MDMGeneralBankInterface/MDMGeneralBankInterface", "mdmgeneralbankinterface_client_ep");
    public final static QName MDMGeneralBankInterfacePt = new QName("http://xmlns.oracle.com/Interface/MDMGeneralBankInterface/MDMGeneralBankInterface", "MDMGeneralBankInterface_pt");
    static {
        URL url = null;
        try {
        	//10.135.16.46:8001
//            url = new URL("http://10.135.16.46:8001/soa-infra/services/interface/MDMGeneralBankInterface/mdmgeneralbankinterface_client_ep?WSDL");
            url = new URL("http://10.135.1.129:7778/soa-infra/services/interface/MDMGeneralBankInterface/mdmgeneralbankinterface_client_ep?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MdmgeneralbankinterfaceClientEp.class.getName())
                .log(java.util.logging.Level.INFO,
//                     "Can not initialize the default wsdl from {0}", "http://10.135.16.46:8001/soa-infra/services/interface/MDMGeneralBankInterface/mdmgeneralbankinterface_client_ep?WSDL");
            "Can not initialize the default wsdl from {0}", "http://10.135.1.129:7778/soa-infra/services/interface/MDMGeneralBankInterface/mdmgeneralbankinterface_client_ep?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public MdmgeneralbankinterfaceClientEp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MdmgeneralbankinterfaceClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MdmgeneralbankinterfaceClientEp() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MdmgeneralbankinterfaceClientEp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MdmgeneralbankinterfaceClientEp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MdmgeneralbankinterfaceClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MDMGeneralBankInterface
     */
    @WebEndpoint(name = "MDMGeneralBankInterface_pt")
    public MDMGeneralBankInterface getMDMGeneralBankInterfacePt() {
        return super.getPort(MDMGeneralBankInterfacePt, MDMGeneralBankInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MDMGeneralBankInterface
     */
    @WebEndpoint(name = "MDMGeneralBankInterface_pt")
    public MDMGeneralBankInterface getMDMGeneralBankInterfacePt(WebServiceFeature... features) {
        return super.getPort(MDMGeneralBankInterfacePt, MDMGeneralBankInterface.class, features);
    }

}
