package com.haier.mdm.qygcx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-26T11:45:46.600+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew", name = "MDMTableConditionDataNew")
@XmlSeeAlso({ObjectFactory.class})
public interface MDMTableConditionDataNew {

    @WebMethod(action = "process")
    @RequestWrapper(localName = "process", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew", className = "com.microfar.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew", className = "com.microfar.ProcessResponse")
    public void process(

            @WebParam(name = "IN_SYS_NAME", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
                    String inSYSNAME,
            @WebParam(name = "IN_MASTER_TYPE", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
                    String inMASTERTYPE,
            @WebParam(name = "IN_TABLE_NAME", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
                    String inTABLENAME,
            @WebParam(name = "IN_FIELDS_VALUE_TABLE", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
                    HAIERMDMFIELDSVALUETABLE inFIELDSVALUETABLE,
            @WebParam(mode = WebParam.Mode.OUT, name = "OUT_RESULT", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
                    javax.xml.ws.Holder<String> outRESULT,
            @WebParam(mode = WebParam.Mode.OUT, name = "OUT_RETMSG", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
                    javax.xml.ws.Holder<String> outRETMSG,
            @WebParam(mode = WebParam.Mode.OUT, name = "OUT_RETCODE", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
                    javax.xml.ws.Holder<String> outRETCODE
    );
}
