
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.haier.webservices.client.hps.trans;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-08-15T09:35:22.629+08:00
 * Generated source version: 3.2.8
 *
 */

@WebService(
                      serviceName = "HpsServiceImplService",
                      portName = "HpsServiceImplPort",
                      targetNamespace = "http://impl.hps.server.webservices.haier.com/",
                      wsdlLocation = "http://localhost:8090/soap/hps?wsdl",
                      endpointInterface = "com.haier.webservices.client.hps.trans.HpsService")

public class HpsServiceImplPortImpl implements HpsService {

    private static final Logger LOG = Logger.getLogger(HpsServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.haier.webservices.client.hps.trans.HpsService#transCode(java.lang.String arg0, java.lang.String arg1)*
     */
    public com.haier.webservices.client.hps.trans.AjaxJson transCode(String arg0, String arg1) {
        LOG.info("Executing operation transCode");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            com.haier.webservices.client.hps.trans.AjaxJson _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
