package com.haier.webservices.client.hps.trans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-08-15T09:35:22.638+08:00
 * Generated source version: 3.2.8
 *
 */
@WebService(targetNamespace = "http://hps.server.webservices.haier.com/", name = "HpsService")
@XmlSeeAlso({ObjectFactory.class})
public interface HpsService {

    @WebMethod
    @RequestWrapper(localName = "transCode", targetNamespace = "http://hps.server.webservices.haier.com/", className = "com.haier.webservices.client.hps.trans.TransCode")
    @ResponseWrapper(localName = "transCodeResponse", targetNamespace = "http://hps.server.webservices.haier.com/", className = "com.haier.webservices.client.hps.trans.TransCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AjaxJson transCode(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );
}
