
package com.haier.webservices.client.hps.trans;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-08-15T09:35:22.619+08:00
 * Generated source version: 3.2.8
 *
 */
public final class HpsService_HpsServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.hps.server.webservices.haier.com/", "HpsServiceImplService");

    private HpsService_HpsServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HpsServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        HpsServiceImplService ss = new HpsServiceImplService(wsdlURL, SERVICE_NAME);
        HpsService port = ss.getHpsServiceImplPort();

        {
        System.out.println("Invoking transCode...");
        String _transCode_arg0 = "";
        String _transCode_arg1 = "";
        AjaxJson _transCode__return = port.transCode(_transCode_arg0, _transCode_arg1);
        System.out.println("transCode.result=" + _transCode__return);


        }

        System.exit(0);
    }

}
