
package com.haier.webservices.client.hps.trans;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-08-15T09:27:58.635+08:00
 * Generated source version: 3.2.8
 *
 */
public final class HpsServiceImpl_HpsServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.hps.server.webservices.haier.com/", "HpsServiceImplService");

    private HpsServiceImpl_HpsServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HpsServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        com.haier.webservices.client.hps.trans.HpsServiceImplService ss = new com.haier.webservices.client.hps.trans.HpsServiceImplService(wsdlURL, SERVICE_NAME);
        HpsServiceImpl port = (HpsServiceImpl) ss.getHpsServiceImplPort();


        System.exit(0);
    }

}
