
package com.haier.webservices.client.hps.trans;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-08-15T09:35:22.642+08:00
 * Generated source version: 3.2.8
 *
 */

public class HpsService_HpsServiceImplPort_Server{

    protected HpsService_HpsServiceImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new HpsServiceImplPortImpl();
        String address = "http://localhost:8090/soap/hps";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new HpsService_HpsServiceImplPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
