package com.haier.webservices.client.hps.trans;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-08-15T09:27:58.656+08:00
 * Generated source version: 3.2.8
 *
 */
@WebService(targetNamespace = "http://impl.hps.server.webservices.haier.com/", name = "HpsServiceImpl")
public interface HpsServiceImpl {
}
