package com.haier.webservices.client.hps.trans;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-08-15T09:35:22.661+08:00
 * Generated source version: 3.2.8
 *
 */
@WebServiceClient(name = "HpsServiceImplService",
                  wsdlLocation = "http://localhost:8090/soap/hps?wsdl",
                  targetNamespace = "http://impl.hps.server.webservices.haier.com/")
public class HpsServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.hps.server.webservices.haier.com/", "HpsServiceImplService");
    public final static QName HpsServiceImplPort = new QName("http://impl.hps.server.webservices.haier.com/", "HpsServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/soap/hps?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HpsServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/soap/hps?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HpsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HpsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HpsServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HpsServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HpsServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HpsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HpsService
     */
    @WebEndpoint(name = "HpsServiceImplPort")
    public HpsService getHpsServiceImplPort() {
        return super.getPort(HpsServiceImplPort, HpsService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HpsService
     */
    @WebEndpoint(name = "HpsServiceImplPort")
    public HpsService getHpsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HpsServiceImplPort, HpsService.class, features);
    }

}
