
package com.haier.webservices.client.mdmTob2b.partner;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-10-12T14:54:29.986+08:00
 * Generated source version: 3.2.8
 *
 */

public class GeneralMDMDataRelease_GeneralMDMDataReleasePt_Server{

    protected GeneralMDMDataRelease_GeneralMDMDataReleasePt_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new GeneralMDMDataRelease_PtImpl();
        String address = "http://bpel.mdm.haier.com:7778/soa-infra/services/interface/GeneralMDMDataRelease/generalmdmdatarelease_client_ep";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new GeneralMDMDataRelease_GeneralMDMDataReleasePt_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
