package com.haier.webservices.client.mdmTob2b.partner;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-10-12T14:54:29.991+08:00
 * Generated source version: 3.2.8
 *
 */
@WebServiceClient(name = "generalmdmdatarelease_client_ep",
                  wsdlLocation = "http://bpel.mdm.haier.com:7778/soa-infra/services/interface/GeneralMDMDataRelease/generalmdmdatarelease_client_ep?WSDL",
                  targetNamespace = "http://xmlns.oracle.com/Interface/GeneralMDMDataRelease/GeneralMDMDataRelease")
public class GeneralmdmdatareleaseClientEp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/Interface/GeneralMDMDataRelease/GeneralMDMDataRelease", "generalmdmdatarelease_client_ep");
    public final static QName GeneralMDMDataReleasePt = new QName("http://xmlns.oracle.com/Interface/GeneralMDMDataRelease/GeneralMDMDataRelease", "GeneralMDMDataRelease_pt");
    static {
        URL url = null;
        try {
            url = new URL("http://bpel.mdm.haier.com:7778/soa-infra/services/interface/GeneralMDMDataRelease/generalmdmdatarelease_client_ep?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeneralmdmdatareleaseClientEp.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://bpel.mdm.haier.com:7778/soa-infra/services/interface/GeneralMDMDataRelease/generalmdmdatarelease_client_ep?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public GeneralmdmdatareleaseClientEp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeneralmdmdatareleaseClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneralmdmdatareleaseClientEp() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GeneralmdmdatareleaseClientEp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GeneralmdmdatareleaseClientEp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GeneralmdmdatareleaseClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GeneralMDMDataRelease
     */
    @WebEndpoint(name = "GeneralMDMDataRelease_pt")
    public GeneralMDMDataRelease getGeneralMDMDataReleasePt() {
        return super.getPort(GeneralMDMDataReleasePt, GeneralMDMDataRelease.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneralMDMDataRelease
     */
    @WebEndpoint(name = "GeneralMDMDataRelease_pt")
    public GeneralMDMDataRelease getGeneralMDMDataReleasePt(WebServiceFeature... features) {
        return super.getPort(GeneralMDMDataReleasePt, GeneralMDMDataRelease.class, features);
    }

}
