
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.haier.webservices.client.mdmTob2b.partner;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-10-12T14:54:29.932+08:00
 * Generated source version: 3.2.8
 *
 */

@javax.jws.WebService(
                      serviceName = "generalmdmdatarelease_client_ep",
                      portName = "GeneralMDMDataRelease_pt",
                      targetNamespace = "http://xmlns.oracle.com/Interface/GeneralMDMDataRelease/GeneralMDMDataRelease",
                      wsdlLocation = "http://bpel.mdm.haier.com:7778/soa-infra/services/interface/GeneralMDMDataRelease/generalmdmdatarelease_client_ep?WSDL",
                      endpointInterface = "com.haier.webservices.client.mdmTob2b.partner.GeneralMDMDataRelease")

public class GeneralMDMDataRelease_PtImpl implements GeneralMDMDataRelease {

    private static final Logger LOG = Logger.getLogger(GeneralMDMDataRelease_PtImpl.class.getName());

    /* (non-Javadoc)
     * @see com.haier.webservices.client.mdmTob2b.partner.GeneralMDMDataRelease#process(java.lang.String inSYSNAME, java.lang.String inMASTERTYPE, java.lang.String inTABLENAME, java.lang.String inSTARTDATE, java.lang.String inENDDATE, java.lang.String inPAGE, java.lang.String inBATCHID, java.lang.String outPAGE, java.lang.String outRESULT, java.lang.String outRETCODE, java.lang.String outALLNUM, java.lang.String outPAGECON, java.lang.String outALLCOUNT, java.lang.String outRETMSG, java.lang.String outBATCHID)*
     */
    public void process(java.lang.String inSYSNAME, java.lang.String inMASTERTYPE, java.lang.String inTABLENAME, java.lang.String inSTARTDATE, java.lang.String inENDDATE, java.lang.String inPAGE, java.lang.String inBATCHID, javax.xml.ws.Holder<java.lang.String> outPAGE, javax.xml.ws.Holder<java.lang.String> outRESULT, javax.xml.ws.Holder<java.lang.String> outRETCODE, javax.xml.ws.Holder<java.lang.String> outALLNUM, javax.xml.ws.Holder<java.lang.String> outPAGECON, javax.xml.ws.Holder<java.lang.String> outALLCOUNT, javax.xml.ws.Holder<java.lang.String> outRETMSG, javax.xml.ws.Holder<java.lang.String> outBATCHID) {
        LOG.info("Executing operation process");
        System.out.println(inSYSNAME);
        System.out.println(inMASTERTYPE);
        System.out.println(inTABLENAME);
        System.out.println(inSTARTDATE);
        System.out.println(inENDDATE);
        System.out.println(inPAGE);
        System.out.println(inBATCHID);
        try {
            java.lang.String outPAGEValue = "";
            outPAGE.value = outPAGEValue;
            java.lang.String outRESULTValue = "";
            outRESULT.value = outRESULTValue;
            java.lang.String outRETCODEValue = "";
            outRETCODE.value = outRETCODEValue;
            java.lang.String outALLNUMValue = "";
            outALLNUM.value = outALLNUMValue;
            java.lang.String outPAGECONValue = "";
            outPAGECON.value = outPAGECONValue;
            java.lang.String outALLCOUNTValue = "";
            outALLCOUNT.value = outALLCOUNTValue;
            java.lang.String outRETMSGValue = "";
            outRETMSG.value = outRETMSGValue;
            java.lang.String outBATCHIDValue = "";
            outBATCHID.value = outBATCHIDValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
