package com.haier.webservices.client.gvs;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.2.0
 * 2019-04-03T10:50:12.340+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "QueryCreditBalanceOfCustomers", 
                  wsdlLocation = "http://10.135.27.4:7001/EAI/service/GVS/Customer/QueryCreditBalanceOfCustomers/QueryCreditBalanceOfCustomers?wsdl",
                  targetNamespace = "http://www.example.org/QueryCreditBalanceOfCustomers/") 
public class QueryCreditBalanceOfCustomers_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/QueryCreditBalanceOfCustomers/", "QueryCreditBalanceOfCustomers");
    public final static QName QueryCreditBalanceOfCustomersSOAP = new QName("http://www.example.org/QueryCreditBalanceOfCustomers/", "QueryCreditBalanceOfCustomersSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://10.135.27.4:7001/EAI/service/GVS/Customer/QueryCreditBalanceOfCustomers/QueryCreditBalanceOfCustomers?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryCreditBalanceOfCustomers_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.135.27.4:7001/EAI/service/GVS/Customer/QueryCreditBalanceOfCustomers/QueryCreditBalanceOfCustomers?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryCreditBalanceOfCustomers_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryCreditBalanceOfCustomers_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryCreditBalanceOfCustomers_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public QueryCreditBalanceOfCustomers_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueryCreditBalanceOfCustomers_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueryCreditBalanceOfCustomers_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns QueryCreditBalanceOfCustomers
     */
    @WebEndpoint(name = "QueryCreditBalanceOfCustomersSOAP")
    public QueryCreditBalanceOfCustomers getQueryCreditBalanceOfCustomersSOAP() {
        return super.getPort(QueryCreditBalanceOfCustomersSOAP, QueryCreditBalanceOfCustomers.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryCreditBalanceOfCustomers
     */
    @WebEndpoint(name = "QueryCreditBalanceOfCustomersSOAP")
    public QueryCreditBalanceOfCustomers getQueryCreditBalanceOfCustomersSOAP(WebServiceFeature... features) {
        return super.getPort(QueryCreditBalanceOfCustomersSOAP, QueryCreditBalanceOfCustomers.class, features);
    }

}
