
package com.haier.webservices.client.gvs;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2019-04-03T10:50:12.274+08:00
 * Generated source version: 3.2.0
 * 
 */
public final class QueryCreditBalanceOfCustomers_QueryCreditBalanceOfCustomersSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/QueryCreditBalanceOfCustomers/", "QueryCreditBalanceOfCustomers");

    private QueryCreditBalanceOfCustomers_QueryCreditBalanceOfCustomersSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = QueryCreditBalanceOfCustomers_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        QueryCreditBalanceOfCustomers_Service ss = new QueryCreditBalanceOfCustomers_Service(wsdlURL, SERVICE_NAME);
        QueryCreditBalanceOfCustomers port = ss.getQueryCreditBalanceOfCustomersSOAP();
        
        {
        System.out.println("Invoking queryCreditBalanceOfCustomers...");
        java.util.List<OMSOUT> _queryCreditBalanceOfCustomers_omsOUT = null;
        java.util.List<OMSIN> _queryCreditBalanceOfCustomers__return = port.queryCreditBalanceOfCustomers(_queryCreditBalanceOfCustomers_omsOUT);
        System.out.println("queryCreditBalanceOfCustomers.result=" + _queryCreditBalanceOfCustomers__return);


        }

        System.exit(0);
    }

}
