/**
 * CreatePlCust2MDM.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.haier.webservices.client.mdm.createcust2mdm;

public interface CreatePlCust2MDM extends java.rmi.Remote {
    public void process(java.lang.String IN_CUSTOMERNUMBER, java.lang.String IN_PARTNERFLAGSP, java.lang.String IN_PARTNERFLAGSH, java.lang.String IN_PARTNERFLAGBP, java.lang.String IN_PARTNERFLAGPY, java.lang.String IN_CUSTOMERTITLE, java.lang.String IN_ACCOUNTGROUP, java.lang.String IN_CUSTOMERNAME, java.lang.String IN_SEARCHTERMS, java.lang.String IN_CUSTOMERCOUNTRY, java.lang.String IN_LANGUAGE, java.lang.String IN_REGION, java.lang.String IN_CITY, java.lang.String IN_STREET, java.lang.String IN_CONTACTPERSON, java.lang.String IN_PHONENUMBER1, java.lang.String IN_VATREGNO, java.lang.String IN_INDUSTRYCLASS, java.lang.String IN_TAXDOCTYPE, java.lang.String IN_LEGAL_PERSON, java.lang.String IN_LEGAL_TYPE, java.lang.String IN_TRAINSTATION, java.lang.String IN_TELEPHONE, java.lang.String IN_BANKCOUNTRY, java.lang.String IN_BANKKEY, java.lang.String IN_ACCOUNTHOLDER, java.lang.String IN_COMPANYCODE, java.lang.String IN_RECONACCOUNT, java.lang.String IN_SORTKEY, java.lang.String IN_CUSTOMER_SUMMARY_GROUP, java.lang.String IN_CURRENCY, java.lang.String IN_CUSTOMER_PRICE_PROCEDURE, java.lang.String IN_ACCT_ASSGMT_GROUP, java.lang.String IN_TAX_CLASSIFICATION, java.lang.String IN_SHIP_CONDITION, java.lang.String IN_POD_RELATION, java.lang.String IN_SALES_REGION, java.lang.String IN_FINANACOUNTNAME, java.lang.String IN_FINANORGN, java.lang.String IN_FINANORGNSHORT, java.lang.String IN_FINANACOUNTCODE, java.lang.String IN_FINANCURRENCY, java.lang.String IN_FINANTYPE, java.lang.String IN_FINANSTATE, java.lang.String IN_SYSNAME, java.lang.String IN_CREATED_BY, java.lang.String OPERATETYPE, java.lang.String UPDATE_BASE, java.lang.String UPDATE_BANK, java.lang.String UPDATE_EXTEND, java.lang.String UPDATE_SALE, java.lang.String UPDATE_COMP, java.lang.String UPDATE_FINANCE, java.lang.String IF_AFFIX, java.lang.String IN_AFFIX_IP, java.lang.String IN_AFFIX_USERNAME, java.lang.String IN_AFFIX_PASSWORD, java.lang.String IN_AFFIX_URL, java.lang.String IN_AFFIX_FILENAME, java.lang.String in_ADDRESS_PROVINCE, java.lang.String in_ADDRESS_CITY, java.lang.String in_ADDRESS_AREA, java.lang.String in_ADDRESS_TOWN, java.lang.String in_ADDRESS_VILLAGE, java.lang.String in_ADDRESS_ROAD, java.lang.String in_ADDRESS_HOUSE_NUMBER, java.lang.String in_ADDRESS_LONGITUDE, java.lang.String in_ADDRESS_LATITUDE, java.lang.String in_SPECIFIC_ADDRESS, java.lang.String IN_INNER_COMPANYCODE, javax.xml.rpc.holders.StringHolder OUT_CUSTOMERCODE, javax.xml.rpc.holders.StringHolder RETCODE, javax.xml.rpc.holders.StringHolder RETMSG) throws java.rmi.RemoteException;
}
