package com.haier.mdm.khzj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-26T19:05:58.710+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM", name = "CreatePlCust2MDM")
@XmlSeeAlso({ObjectFactory.class})
public interface CreatePlCust2MDM {

    @WebMethod(action = "process")
    @RequestWrapper(localName = "process", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM", className = "com.microfar.custom.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM", className = "com.microfar.custom.ProcessResponse")
    public void process(

            @WebParam(name = "IN_CUSTOMERNUMBER", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCUSTOMERNUMBER,
            @WebParam(name = "IN_PARTNERFLAGSP", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inPARTNERFLAGSP,
            @WebParam(name = "IN_PARTNERFLAGSH", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inPARTNERFLAGSH,
            @WebParam(name = "IN_PARTNERFLAGBP", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inPARTNERFLAGBP,
            @WebParam(name = "IN_PARTNERFLAGPY", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inPARTNERFLAGPY,
            @WebParam(name = "IN_CUSTOMERTITLE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCUSTOMERTITLE,
            @WebParam(name = "IN_ACCOUNTGROUP", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inACCOUNTGROUP,
            @WebParam(name = "IN_CUSTOMERNAME", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCUSTOMERNAME,
            @WebParam(name = "IN_SEARCHTERMS", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inSEARCHTERMS,
            @WebParam(name = "IN_CUSTOMERCOUNTRY", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCUSTOMERCOUNTRY,
            @WebParam(name = "IN_LANGUAGE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inLANGUAGE,
            @WebParam(name = "IN_REGION", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inREGION,
            @WebParam(name = "IN_CITY", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCITY,
            @WebParam(name = "IN_STREET", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inSTREET,
            @WebParam(name = "IN_CONTACTPERSON", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCONTACTPERSON,
            @WebParam(name = "IN_PHONENUMBER1", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inPHONENUMBER1,
            @WebParam(name = "IN_VATREGNO", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inVATREGNO,
            @WebParam(name = "IN_INDUSTRYCLASS", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inINDUSTRYCLASS,
            @WebParam(name = "IN_TAXDOCTYPE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inTAXDOCTYPE,
            @WebParam(name = "IN_LEGAL_PERSON", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inLEGALPERSON,
            @WebParam(name = "IN_LEGAL_TYPE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inLEGALTYPE,
            @WebParam(name = "IN_TRAINSTATION", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inTRAINSTATION,
            @WebParam(name = "IN_TELEPHONE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inTELEPHONE,
            @WebParam(name = "IN_BANKCOUNTRY", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inBANKCOUNTRY,
            @WebParam(name = "IN_BANKKEY", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inBANKKEY,
            @WebParam(name = "IN_ACCOUNTHOLDER", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inACCOUNTHOLDER,
            @WebParam(name = "IN_COMPANYCODE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCOMPANYCODE,
            @WebParam(name = "IN_RECONACCOUNT", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inRECONACCOUNT,
            @WebParam(name = "IN_SORTKEY", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inSORTKEY,
            @WebParam(name = "IN_CUSTOMER_SUMMARY_GROUP", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCUSTOMERSUMMARYGROUP,
            @WebParam(name = "IN_CURRENCY", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCURRENCY,
            @WebParam(name = "IN_CUSTOMER_PRICE_PROCEDURE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCUSTOMERPRICEPROCEDURE,
            @WebParam(name = "IN_ACCT_ASSGMT_GROUP", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inACCTASSGMTGROUP,
            @WebParam(name = "IN_TAX_CLASSIFICATION", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inTAXCLASSIFICATION,
            @WebParam(name = "IN_SHIP_CONDITION", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inSHIPCONDITION,
            @WebParam(name = "IN_POD_RELATION", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inPODRELATION,
            @WebParam(name = "IN_SALES_REGION", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inSALESREGION,
            @WebParam(name = "IN_FINANACOUNTNAME", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inFINANACOUNTNAME,
            @WebParam(name = "IN_FINANORGN", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inFINANORGN,
            @WebParam(name = "IN_FINANORGNSHORT", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inFINANORGNSHORT,
            @WebParam(name = "IN_FINANACOUNTCODE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inFINANACOUNTCODE,
            @WebParam(name = "IN_FINANCURRENCY", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inFINANCURRENCY,
            @WebParam(name = "IN_FINANTYPE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inFINANTYPE,
            @WebParam(name = "IN_FINANSTATE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inFINANSTATE,
            @WebParam(name = "IN_SYSNAME", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inSYSNAME,
            @WebParam(name = "IN_CREATED_BY", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inCREATEDBY,
            @WebParam(name = "OPERATETYPE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String operatetype,
            @WebParam(name = "UPDATE_BASE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String updateBASE,
            @WebParam(name = "UPDATE_BANK", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String updateBANK,
            @WebParam(name = "UPDATE_EXTEND", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String updateEXTEND,
            @WebParam(name = "UPDATE_SALE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String updateSALE,
            @WebParam(name = "UPDATE_COMP", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String updateCOMP,
            @WebParam(name = "UPDATE_FINANCE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String updateFINANCE,
            @WebParam(name = "IF_AFFIX", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String ifAFFIX,
            @WebParam(name = "IN_AFFIX_IP", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inAFFIXIP,
            @WebParam(name = "IN_AFFIX_USERNAME", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inAFFIXUSERNAME,
            @WebParam(name = "IN_AFFIX_PASSWORD", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inAFFIXPASSWORD,
            @WebParam(name = "IN_AFFIX_URL", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inAFFIXURL,
            @WebParam(name = "IN_AFFIX_FILENAME", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inAFFIXFILENAME,
            @WebParam(name = "in_ADDRESS_PROVINCE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inADDRESSPROVINCE,
            @WebParam(name = "in_ADDRESS_CITY", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inADDRESSCITY,
            @WebParam(name = "in_ADDRESS_AREA", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inADDRESSAREA,
            @WebParam(name = "in_ADDRESS_TOWN", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inADDRESSTOWN,
            @WebParam(name = "in_ADDRESS_VILLAGE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inADDRESSVILLAGE,
            @WebParam(name = "in_ADDRESS_ROAD", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inADDRESSROAD,
            @WebParam(name = "in_ADDRESS_HOUSE_NUMBER", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inADDRESSHOUSENUMBER,
            @WebParam(name = "in_ADDRESS_LONGITUDE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inADDRESSLONGITUDE,
            @WebParam(name = "in_ADDRESS_LATITUDE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inADDRESSLATITUDE,
            @WebParam(name = "in_SPECIFIC_ADDRESS", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inSPECIFICADDRESS,
            @WebParam(name = "IN_INNER_COMPANYCODE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    String inINNERCOMPANYCODE,
            @WebParam(mode = WebParam.Mode.OUT, name = "OUT_CUSTOMERCODE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    javax.xml.ws.Holder<String> outCUSTOMERCODE,
            @WebParam(mode = WebParam.Mode.OUT, name = "RETCODE", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    javax.xml.ws.Holder<String> retcode,
            @WebParam(mode = WebParam.Mode.OUT, name = "RETMSG", targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
                    javax.xml.ws.Holder<String> retmsg
    );
}
