
package com.haier.webservices.client.mdmTob2b.source;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2020-02-24T11:56:48.137+08:00
 * Generated source version: 3.2.8
 *
 */

public class MDMTableConditionDataNew_MDMTableConditionDataNewPt_Server{

    protected MDMTableConditionDataNew_MDMTableConditionDataNewPt_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MDMTableConditionDataNew_PtImpl();
        String address = "http://bpel.mdm.haier.com:7778/soa-infra/services/interface/MDMTableConditionDataNew/mdmtableconditiondatanew_client_ep";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new MDMTableConditionDataNew_MDMTableConditionDataNewPt_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
