package com.haier.webservices.client.mdmTob2b.source;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2020-02-24T11:56:47.995+08:00
 * Generated source version: 3.2.8
 *
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew", name = "MDMTableConditionDataNew")
@XmlSeeAlso({ObjectFactory.class})
public interface MDMTableConditionDataNew {

    @WebMethod(action = "process")
    @RequestWrapper(localName = "process", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew", className = "com.haier.webservices.client.mdmTob2b.source.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew", className = "com.haier.webservices.client.mdmTob2b.source.ProcessResponse")
    public void process(
        @WebParam(name = "IN_SYS_NAME", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
        java.lang.String inSYSNAME,
        @WebParam(name = "IN_MASTER_TYPE", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
        java.lang.String inMASTERTYPE,
        @WebParam(name = "IN_TABLE_NAME", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
        java.lang.String inTABLENAME,
        @WebParam(name = "IN_FIELDS_VALUE_TABLE", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
        com.haier.webservices.client.mdmTob2b.source.HAIERMDMFIELDSVALUETABLE inFIELDSVALUETABLE,
        @WebParam(mode = WebParam.Mode.OUT, name = "OUT_RESULT", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
        javax.xml.ws.Holder<java.lang.String> outRESULT,
        @WebParam(mode = WebParam.Mode.OUT, name = "OUT_RETMSG", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
        javax.xml.ws.Holder<java.lang.String> outRETMSG,
        @WebParam(mode = WebParam.Mode.OUT, name = "OUT_RETCODE", targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew")
        javax.xml.ws.Holder<java.lang.String> outRETCODE
    );
}
