
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.haier.webservices.client.mdmTob2b.source;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2020-02-24T11:56:47.981+08:00
 * Generated source version: 3.2.8
 *
 */

@javax.jws.WebService(
                      serviceName = "mdmtableconditiondatanew_client_ep",
                      portName = "MDMTableConditionDataNew_pt",
                      targetNamespace = "http://xmlns.oracle.com/Interface/MDMTableConditionDataNew/MDMTableConditionDataNew",
                      wsdlLocation = "http://bpel.mdm.haier.com:7778/soa-infra/services/interface/MDMTableConditionDataNew/mdmtableconditiondatanew_client_ep?WSDL",
                      endpointInterface = "com.haier.webservices.client.mdmTob2b.source.MDMTableConditionDataNew")

public class MDMTableConditionDataNew_PtImpl implements MDMTableConditionDataNew {

    private static final Logger LOG = Logger.getLogger(MDMTableConditionDataNew_PtImpl.class.getName());

    /* (non-Javadoc)
     * @see com.haier.webservices.client.mdmTob2b.source.MDMTableConditionDataNew#process(java.lang.String inSYSNAME, java.lang.String inMASTERTYPE, java.lang.String inTABLENAME, com.haier.webservices.client.mdmTob2b.source.HAIERMDMFIELDSVALUETABLE inFIELDSVALUETABLE, java.lang.String outRESULT, java.lang.String outRETMSG, java.lang.String outRETCODE)*
     */
    public void process(java.lang.String inSYSNAME, java.lang.String inMASTERTYPE, java.lang.String inTABLENAME, com.haier.webservices.client.mdmTob2b.source.HAIERMDMFIELDSVALUETABLE inFIELDSVALUETABLE, javax.xml.ws.Holder<java.lang.String> outRESULT, javax.xml.ws.Holder<java.lang.String> outRETMSG, javax.xml.ws.Holder<java.lang.String> outRETCODE) {
        LOG.info("Executing operation process");
        System.out.println(inSYSNAME);
        System.out.println(inMASTERTYPE);
        System.out.println(inTABLENAME);
        System.out.println(inFIELDSVALUETABLE);
        try {
            java.lang.String outRESULTValue = "";
            outRESULT.value = outRESULTValue;
            java.lang.String outRETMSGValue = "";
            outRETMSG.value = outRETMSGValue;
            java.lang.String outRETCODEValue = "";
            outRETCODE.value = outRETCODEValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
